name: Manual Trigger with Params

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of Person to greet'
        required: true
        type: string
      greeting:
        description: 'Type of greeting'
        required: true
        type: string
      data:
        description: 'Base64 Encoded content of a file'
        required: true
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Decode File Content
        run: |
          echo "${{ inputs.data }}" | base64 --decode > ./decoded_file.txt

      - name: Display Greeting
        run: |
          echo "${{ inputs.greeting }}, ${{ inputs.name }}!"

      - name: Display File Content
        run: |
          echo "Content of the file:"
          cat ./decoded_file.txt